/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type PortableTextBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h2' | 'h3' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        newTab?: boolean;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: 'image';
      _key: string;
    }
>;

export type Seo = {
  _type: 'seo';
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Activity = {
  _id: string;
  _type: 'activity';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  language: 'en' | 'de' | 'fr' | 'nl' | 'es' | 'it';
  eyebrow?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  description?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type JournalPost = {
  _id: string;
  _type: 'journalPost';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  language: 'en' | 'de' | 'fr' | 'nl' | 'es' | 'it';
  publishedAt: string;
  author?: string;
  excerpt?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  body: PortableTextBody;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  language: 'en' | 'de' | 'fr' | 'nl' | 'es' | 'it';
  eyebrow?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  body: PortableTextBody;
  seo?: Seo;
};

export type Homepage = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language: 'en' | 'de' | 'fr' | 'nl' | 'es' | 'it';
  heroOverride?: {
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: 'image';
    };
    primaryCta?: {
      label?: string;
      href?: string;
    };
  };
  brandStatementOverride?: {
    eyebrow?: string;
    headline?: string;
    body?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | PortableTextBody
  | Seo
  | Activity
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | JournalPost
  | Page
  | Homepage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage" && language in [$locale, "en"]]  | order(language == $locale desc, language == "en" desc)[0]
export type HomepageQueryResult = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language: 'de' | 'en' | 'es' | 'fr' | 'it' | 'nl';
  heroOverride?: {
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: 'image';
    };
    primaryCta?: {
      label?: string;
      href?: string;
    };
  };
  brandStatementOverride?: {
    eyebrow?: string;
    headline?: string;
    body?: string;
  };
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug && language in [$locale, "en"]]  | order(language == $locale desc, language == "en" desc)[0] {    _id,    title,    "slug": slug.current,    language,    eyebrow,    heroImage,    body,    seo  }
export type PageQueryResult = {
  _id: string;
  title: string;
  slug: string;
  language: 'de' | 'en' | 'es' | 'fr' | 'it' | 'nl';
  eyebrow: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  } | null;
  body: PortableTextBody;
  seo: Seo | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: journalPostQuery
// Query: *[_type == "journalPost" && slug.current == $slug && language in [$locale, "en"]]  | order(language == $locale desc, language == "en" desc)[0] {    _id,    title,    "slug": slug.current,    language,    publishedAt,    author,    excerpt,    heroImage,    body,    seo  }
export type JournalPostQueryResult = {
  _id: string;
  title: string;
  slug: string;
  language: 'de' | 'en' | 'es' | 'fr' | 'it' | 'nl';
  publishedAt: string;
  author: string | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  } | null;
  body: PortableTextBody;
  seo: Seo | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: journalIndexQuery
// Query: *[_type == "journalPost" && language in [$locale, "en"]]  | order(publishedAt desc)  [$start...$end] {    _id,    title,    "slug": slug.current,    language,    publishedAt,    author,    excerpt,    heroImage  }
export type JournalIndexQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  language: 'de' | 'en' | 'es' | 'fr' | 'it' | 'nl';
  publishedAt: string;
  author: string | null;
  excerpt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: journalCountQuery
// Query: count(*[_type == "journalPost" && language in [$locale, "en"]])
export type JournalCountQueryResult = number;

// Source: src/lib/sanity/queries.ts
// Variable: activityListQuery
// Query: *[_type == "activity" && language in [$locale, "en"]]  | order(language == $locale desc, language == "en" desc) {    _id,    title,    "slug": slug.current,    language,    eyebrow,    heroImage,    description  }
export type ActivityListQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  language: 'de' | 'en' | 'es' | 'fr' | 'it' | 'nl';
  eyebrow: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  } | null;
  description: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "homepage" && language in [$locale, "en"]]\n  | order(language == $locale desc, language == "en" desc)[0]\n': HomepageQueryResult;
    '\n  *[_type == "page" && slug.current == $slug && language in [$locale, "en"]]\n  | order(language == $locale desc, language == "en" desc)[0] {\n    _id,\n    title,\n    "slug": slug.current,\n    language,\n    eyebrow,\n    heroImage,\n    body,\n    seo\n  }\n': PageQueryResult;
    '\n  *[_type == "journalPost" && slug.current == $slug && language in [$locale, "en"]]\n  | order(language == $locale desc, language == "en" desc)[0] {\n    _id,\n    title,\n    "slug": slug.current,\n    language,\n    publishedAt,\n    author,\n    excerpt,\n    heroImage,\n    body,\n    seo\n  }\n': JournalPostQueryResult;
    '\n  *[_type == "journalPost" && language in [$locale, "en"]]\n  | order(publishedAt desc)\n  [$start...$end] {\n    _id,\n    title,\n    "slug": slug.current,\n    language,\n    publishedAt,\n    author,\n    excerpt,\n    heroImage\n  }\n': JournalIndexQueryResult;
    '\n  count(*[_type == "journalPost" && language in [$locale, "en"]])\n': JournalCountQueryResult;
    '\n  *[_type == "activity" && language in [$locale, "en"]]\n  | order(language == $locale desc, language == "en" desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    language,\n    eyebrow,\n    heroImage,\n    description\n  }\n': ActivityListQueryResult;
  }
}
